default_stages: [commit, push]
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: black (formatting)
        language_version: python3.12
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8 (linting)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit (security)
        description: "Bandit is a tool for finding common security issues in Python code"
        entry: bandit
        language: python
        types: [python]
        args: [--configfile, bandit.yml]
  - repo: local
    hooks:
      - id: pyright
        name: pyright (types)
        entry: bash -c  'pyright -p pyrightconfig.json'
        language: system
      - id: pylint
        name: pylint (linting)
        entry: pylint
        language: system
        types: [python]
        args: [--rcfile=setup.cfg]
